import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import MenuButtom from "@/Components/MenuButtom";
import NavSearch from "@/Components/NavSearch";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:flex flex-row justify-between items-center bg-slate-500">
          <nav className="md:flex flex-wrap  gap-4 bg-slate-500  list-none p-2 w-full ">
            <Link href={"/"} ><li className=" btn bg-slate-700 p-4 rounded">Home</li></Link>
            <Link href={"/about"} ><li className=" btn bg-slate-700 p-4 rounded">About</li></Link>
            <Link href={"/blog"}><li className="btn bg-slate-700 p-4 rounded">Blog Page</li></Link>
            <Link href={"/"}><li className="btn  bg-slate-700 p-4 rounded">Next Page</li></Link>
            <Link href={"/dashborad"}><li className=" btn list-none p-4 bg-green-500">DashBoard</li></Link>
          </nav>
          <div className="py-2 px-2"><NavSearch /></div>
        </div>
        <section className="p-4">{children}</section>
        <div className="pb-4 w-fit mx-auto" >
          <MenuButtom />
        </div>
      </body>
    </html>
  );
}
